### ISSUE TITLE
Turn off syntax checking?

### ISSUE THREAD

**Issue by bartonhammond** [ymcatar/gitbook-plugin-ace#1]
First, thanks for making this plugin!

I'd like to have the option for [Syntax-validation](https://github.com/ajaxorg/ace/wiki/Syntax-validation) to be turned off.

<img width="467" alt="screen shot 2015-09-28 at 10 51 42 am" src="https://cloud.githubusercontent.com/assets/1282364/10140808/11b6ddac-65cf-11e5-8026-52a6377ac22b.png">

**Comment by ymcatar** [comment]
Thanks for the feature request. I've added the support for that.

You can add a ```check=true``` parameter onto the opening tag of the plugin.

```
{%ace edit=false, lang='javascript', check=true%}
var test = [
	somethingIsWrong: 'withThis';
];
{%endace%}
```

**Comment by bartonhammond** [comment]
works great!
