### ISSUE TITLE
Markdown with code block {{}} breaks 

### ISSUE THREAD

**Issue by roachsinai** [ymcatar/gitbook-plugin-ace#10]
error: `Template render error: (/home/*/*.md) [Line 50, Column 21] expected variable end`.  

If has `{{other codes}}`, just change `{{code}}` to `{ {code} }` can solve this problem.

I use ace in this method: `{%ace edit=true, lang='c_cpp'%}`.

**Don't know should I post this thing by a new issue**. Just hope people don,t waste time.

**Comment by ymcatar** [comment]
oh, there is some problem with my regular expression.
thanks for reporting, I will fix it asap

**Comment by roachsinai** [comment]
:+1:

**Comment by ymcatar** [comment]
@roachsinai  It should be fixed in version 0.3.2. Thanks for reporting.

**Comment by roachsinai** [comment]
Yeah! Test Success.
