### ISSUE TITLE
How to use it as default plugin for code block?

### ISSUE THREAD

**Issue by KINGSABRI** [ymcatar/gitbook-plugin-ace#13]
Hi 
First, thanks for making this plugin available. 

My question is, can we make gitbook use ace plugin as it's default behavior? in another word, I want to avoid writing tags like `{%ace edit=true, lang='ruby'%}` and instead use the normal markdown ` ```ruby `  tag and make gitbook understand it and use **ace** plugin instead of **highlight**?

**Comment by ymcatar** [comment]
Don't think it is possible with gitbook 3.x, however, I might rewrite the plugin for gitbook 4.0+ and I will see if it is possible once their api are completed.
