### ISSUE TITLE
lack of </div>

### ISSUE THREAD

**Issue by nju-ics** [ymcatar/gitbook-plugin-ace#2]
Hi. I try to use this plugin in a div block, but some contents after the block go into the block. I check the generated html code, and I find that this plugin generates two `<div>` tag with one `</div>` tag.

In line 25 of `index.js`, the current code is
```
return '<div class="ace"><div class="aceCode" data-config='+JSON.stringify(config)+'>'+escape(blk.body.trim())+'<br></div>';
```
I think one more </div> tag should be appended to the code:
```
return '<div class="ace"><div class="aceCode" data-config='+JSON.stringify(config)+'>'+escape(blk.body.trim())+'<br></div></div>';
```
Please check it. Thanks!

**Comment by ymcatar** [comment]
Thanks! I updated the plugin according to your suggestion. Please check if it is working.
