### ISSUE TITLE
Use ace in the GitBook.com book editor

### ISSUE THREAD

**Issue by FelipeCardoso89** [ymcatar/gitbook-plugin-ace#4]
Is it possible to use ace plugin in the online book editor at GitBook.com?
Acer appear at GitBook plugin store, but the ace's code example do not work in the on-line editor.

Thank you.

**Comment by FelipeCardoso89** [comment]
Never mind. It works great. I miss understood how the ace works.

**Comment by ymcatar** [comment]
Actually, the preview on gitbook.com doesn't seem to support live preview of plugins and there is no way for me to add support since gitbook itself doesn't provide a way for me to add it. So you will only be able to see the plugin working in the generated page.
