### ISSUE TITLE
Breaks every time

### ISSUE THREAD

**Issue by maegul** [ymcatar/gitbook-plugin-ace#6]
It has never worked.

Always get an error like the following:

Template render error: (/tmp/book/acetest.md) [Line 4, Column 22]
  parseSignature: expected comma after expression

**Comment by ymcatar** [comment]
Can you include the markdown code for me to locate the bug/problem?

**Comment by maegul** [comment]
I took the example for the Repo README.md.

I also tried removing certain elements such as the comment and include lines.  Neither seemed to help.

{%ace edit=true, lang='c_cpp'%}
// This is a hello world program for C.
#include <stdio.h>

int main(){
  printf("Hello World!");
  return 1;
}
{%endace%}

**Comment by ymcatar** [comment]
The code above should work. I tried it on gitbook.io (see [here](https://raw.githubusercontent.com/ymcatar/gitbook-test/master/testing_ace.md)) and also my local build and it is working as expected.

Mind if uploading the whole folders so I can take a look of the config?

**Comment by keyunluo** [comment]
There are some problems when I use ace.

{%ace edit=true, lang='c_cpp', check=false, theme='monokai'%}
// Define an array .
 typedef int myArrayType [101];
{%endace%}

and the result would be  ：

\/\/ Define an array .
 typedef int myArrayType \[101\];

My plugins ：
"plugins": [
        "ace",
        "katex",
        "richquotes",
        "github",
        "edit-link",
        "emphasize",
        "tbfed-pagefooter",
        "ga"
    ]

**Comment by ymcatar** [comment]
That is a problem with gitbook 3.0+. This issue shall be fixed in the next release of the plugin.

**Comment by ymcatar** [comment]
It should be fixed in 0.3.0, please reopen the issue if you find out any problem.
