### ISSUE TITLE
is it possible to make this work also in the Gitbook editor?

### ISSUE THREAD

**Issue by jserodio** [ymcatar/gitbook-plugin-ace#7]
Can you preview the plugin's work in the Gitbook Editor Application? or gitbook online editor? I only see it working when I hit the "Read" button in the gitbook website. Is it possible?

**Comment by ymcatar** [comment]
No, since in gitbook.io the plugin script has to be ran by the server to produce the plugin output, if gitbook editor do not do that, then I'm sorry that I can't quite make the preview works on Gitbook Editor.
